version: 0.2
phases:
  install:
    commands:
      - npm install -g artillery@latest
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=AKIA5WEHMKA752A7CU4K
      - export AWS_SECRET_ACCESS_KEY=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
      - artillery run blitz.yml
